FROM node:18

WORKDIR /app  # Set working directory inside the container

COPY package.json package-lock.json ./
RUN npm install  # Install dependencies inside the container

COPY . . 

CMD ["node", "index.js"]
